// Generated by Wrangler by running `wrangler types`

interface Env {
	CORS_ORIGIN: "http://localhost:5173" | "cloudflare-app-5gj.pages.dev";
	ENVIRONMENT: "dev" | "staging" | "production";
	MY_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").MyDurableObject>;
	DB: D1Database;
}
